version: '3.1'
services:
  web:
    image: nginx:mainline-alpine
    restart: always
    depends_on:
      - gitbucket
      - redmine
      - admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf//nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.template:ro
      - ./log/nginx:/var/log/nginx
      # - ./secrets/certs:/etc/nginx/certs:ro
      - ./www/html:/usr/share/www/html:ro
    environment:
      TZ: Asia/Tokyo
      NGINX_HOST: 190ikp.com
    networks:
      - front
    command: >
      /bin/sh -c
      "envsubst '$$NGINX_HOST'
      < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
  
  gitbucket:
    image: f99aq8ove/gitbucket:latest
    restart: always
    depends_on:
      - ldap
    ports:
      - "7996:8080"
      # # for SSH access
      - "29418:29418"
    volumes:
      # リポジトリのディレクトリは ./data/gitbucket/repositories
      - ./data/gitbucket:/gitbucket
    environment:
      TZ: Asia/Tokyo
    networks:
      - front
      - back

  redmine:
    image: redmine:4.0
    restart: always
    depends_on:
      - db
      - ldap
    ports: 
      - "65457:3000"
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
      - ./data/redmine/themes:/usr/src/redmine/themes
      - ./log/redmine:/usr/src/redmine/log
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - front
      - back
    secrets:
      - db_redmine_password
  
  db:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - ./data/redmine/db:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF8
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - back
    secrets:
      - db_redmine_password

  # 以下はDocker Securityが使えるように後々拡張するつもり

  admin:
    # for more info:  https://github.com/osixia/docker-phpLDAPadmin
    image: osixia/phpldapadmin:0.7.2
    depends_on:
      - ldap
    ports:
      - "4433:4433"
    # volumes:
      # - ./secrets/certs:/container/service/phpldapadmin/assets/apache2/certs:ro
      # # 設定は./conf/ldap_admin/env.ymlに記述
      # - ./conf/ldap_admin/env.yml:/container/environment/01-custom/env.yaml:ro
    environment:
      TZ: Asia/Tokyo
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      # 後々HTTPS有効化する
      PHPLDAPADMIN_HTTPS: "false"
      # 以下はデフォルト値
      # PHPLDAPADMIN_HTTPS_CRT_FILENAME: server.crt
      # PHPLDAPADMIN_HTTPS_KEY_FILENAME: server.key
      # PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: ca.crt
    networks:
      - front
      - back

  ldap:
    image: osixia/openldap:1.2.3
    restart: always
    ports:
      - "636:636"
    volumes:
      - ./data/ldap/db:/var/lib/ldap
      # - ./conf/ldap:/etc/ldap/slapd.d
    environment:
      TZ: Asia/Tokyo
      # 以下は適当に書き換えること
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "*190ikp.com"
      LDAP_ADMIN_PASSWORD: "root"
      LDAP_CONFIG_PASSWORD: "pass"
      HOSTNAME: 190ikp.com
    networks:
      - back

  # ldap-backup:
  #   image: osixia/openldap-backup:1.2.3
  #   restart: always
  #   depends_on:
  #     - ldap
  #   volumes:
  #     - ./data/ldap/backup:/data/backup
  #   environment:
  #     TZ: Asia/Tokyo
  #     LDAP_BACKUP_CONFIG_CRON_EXP: "0 5 * * *"
  #   networks:
  #     - back

networks:
  # 後々frontのみホストとつながるようにする予定
  front:
  back:

secrets:
  db_redmine_password:
    file: ./secrets/db_redmine_password.txt