version: '3.1'
services:
  web:
    image: nginx:mainline-alpine
    container_name: nginx
    depends_on:
      - gitbucket
      - redmine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # ログファイル置き場
      - ./log/nginx:/var/log/nginx
      # indexファイルを ./www に置く
      - ./www:/usr/share/nginx/html:ro
    networks:
      - front
  
  gitbucket:
    image: f99aq8ove/gitbucket:latest
    container_name: gitbucket
    ports:
      - "7996:8080"
      # # for SSH access
      - "29148:29418"
    volumes:
      - ./gitbucket:/gitbucket
      # リポジトリのディレクトリは ./gitbucket/repositories
    networks:
      - front

  redmine:
    image: redmine:4.0
    container_name: redmine
    depends_on:
      - db
    ports: 
      - "65457:3000"
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - front
      - back
    secrets:
      - db_redmine_password
  
  db:
    image: postgres:11.1-alpine
    container_name: db
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./redmine/db:/var/lib/postgresql/daa
    environment:
      LANG: ja_JP.UTF8
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - back
    secrets:
      - db_redmine_password


  # ldap:
  #   image: osixia/openldap
  #   ports:
  #     - "389:389"
  #   environment:
  #     LDAP_ORGANISATION: "example"
  #     LDAP_DOMAIN: "example.com"
  #     LDAP_ADMIN_PASSWORD: "root"
  #     LDAP_CONFIG_PASSWORD: "pass"
        
  # phpldapadmin:
  #   image: osixia/phpldapadmin
  #   ports:
  #     - "7347:2398"
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: ldap
  #     PHPLDAPADMIN_HTTPS: "false"

networks:
  front:
  # 後々frontのみホストとつながるようにする予定
  back:

secrets:
  db_redmine_password:
    file: ./secrets/db_redmine_password.txt