version: '3.1'
services:
  proxy:
    image: steveltn/https-portal:1.6.0
    restart: always
    depends_on:
      - gitbucket
      - redmine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx/proxy:/var/log/nginx
      - ./www/vhosts:/var/www/vhosts:ro
    environment:
      TZ: Asia/Tokyo
      DOMAINS: 'example.com, git.example.com -> http://gitbucket:8080, redmine.example.com -> http://redmine:3000'
      STAGE: 'local'
    networks:
      - front
  
  # web:
  #   image: nginx:mainline-alpine
  #   restart: always
  #   depends_on:
  #     - gitbucket
  #     - redmine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.template:ro
  #     - ./log/nginx:/var/log/nginx
  #     # - ./conf/logrotate.d/nginx:/etc/logrotate.d/nginx:ro
  #     # - ./secrets/certs:/etc/nginx/certs:ro
  #     - ./www/html:/usr/share/www/html:ro
  #   environment:
  #     TZ: Asia/Tokyo
  #     # NGINX_HOST: example.com
  #   networks:
  #     - front
  #   # command: >
  #   #   /bin/sh -c
  #   #   "envsubst '$$NGINX_HOST'
  #   #   < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf
  #   #   && nginx -g 'daemon off;'"
  
  gitbucket:
    image: 190ikp/gitbucket:latest
    restart: always
    ports:
      - "8080:8080"
      # for SSH access
      - "29418:29418"
    volumes:
      - ./data/gitbucket:/gitbucket
    environment:
      TZ: Asia/Tokyo
    networks:
      - front
      - back

  redmine:
    image: redmine:4.0
    restart: always
    depends_on:
      - db
    ports: 
      - "3000:3000"
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
      - ./data/redmine/themes:/usr/src/redmine/themes
      - ./log/redmine:/usr/src/redmine/log
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - front
      - back
    secrets:
      - db_redmine_password

  # jenkins:
  #   image: jenkins:alpine
  #   restart: always
  #   ports:
  #     - "3030"
  #   networks:
  #     - front

  db:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - ./data/redmine/db:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF8
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD_FILE: /run/secrets/db_redmine_password
    networks:
      - back
    secrets:
      - db_redmine_password

networks:
  front:
  back:

secrets:
  db_redmine_password:
    file: ./secrets/db_redmine_password.txt